[phases.setup]
nixPkgs = ['python312', 'postgresql']

[phases.install]
cmds = [
  'pip install -r requirements.txt'
]

[phases.build]
cmds = [
  'python manage.py collectstatic --noinput'
]

[start]
cmd = 'python manage.py migrate && gunicorn innoquim.wsgi:application --bind 0.0.0.0:$PORT'
